services:
  - type: web
    name: motion-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python serve.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
